/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.ModalEditar;
import telas.ModalCadastros.*;
import Entidades.Paciente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Davy
 */
public class EditarCadastroPacientes extends javax.swing.JFrame {

    /**
     * Creates new form ModalCadastrarPacientes
     */
    
    public EditarCadastroPacientes(){
        initComponents();
    }
    
    public EditarCadastroPacientes(Paciente paciente) {
        initComponents();
        txtIdPacientes.setText(paciente.getId().toString());
        txtPacienteNome.setText(paciente.getNome());
        txtPacienteSenha.setText(paciente.getSenha());
        txtPacienteIdade.setText(Integer.toString(paciente.getIdade()));
        txtPacienteTelefone.setText(Integer.toString(paciente.getTelefone()));
        txtPacienteCPF.setText(Integer.toString(paciente.getCPF()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarPacientes = new javax.swing.JButton();
        txtPacienteNome = new javax.swing.JTextField();
        txtPacienteSenha = new javax.swing.JTextField();
        txtPacienteTelefone = new javax.swing.JTextField();
        txtPacienteCPF = new javax.swing.JTextField();
        txtPacienteIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdPacientes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnEditarPacientes.setText("Aplicar");
        btnEditarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarPacientes);
        btnEditarPacientes.setBounds(30, 350, 140, 24);

        txtPacienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPacienteNome);
        txtPacienteNome.setBounds(120, 90, 280, 24);
        getContentPane().add(txtPacienteSenha);
        txtPacienteSenha.setBounds(120, 140, 280, 24);

        txtPacienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPacienteTelefone);
        txtPacienteTelefone.setBounds(120, 300, 280, 24);

        txtPacienteCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtPacienteCPF);
        txtPacienteCPF.setBounds(120, 240, 280, 24);
        getContentPane().add(txtPacienteIdade);
        txtPacienteIdade.setBounds(120, 190, 280, 24);

        jLabel1.setText("CPF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 300, 60, 16);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 50, 16);

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 50, 16);

        jLabel4.setText("Idade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 50, 16);

        jLabel5.setText("Telefone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 60, 16);

        txtIdPacientes.setEnabled(false);
        txtIdPacientes.setFocusable(false);
        txtIdPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPacientes);
        txtIdPacientes.setBounds(120, 40, 280, 24);

        jLabel6.setText("ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 40, 41, 16);

        setSize(new java.awt.Dimension(459, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacientesActionPerformed
        // TODO add your handling code here:
        Paciente paciente  = new Paciente();
        paciente.setNome(txtPacienteNome.getText());
        paciente.setSenha(txtPacienteSenha.getText());
        paciente.setIdade(Integer.parseInt(txtPacienteIdade.getText()));
        paciente.setTelefone(txtPacienteTelefone.getText());
        paciente.setCPF(Integer.parseInt(txtPacienteCPF.getText()));
        paciente.setId(txtIdPacientes.getText());
        
        try {
            paciente.editarPacientes();
        } catch (SQLException ex) {
            Logger.getLogger(EditarCadastroPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        limparCampos();
        
    }//GEN-LAST:event_btnEditarPacientesActionPerformed

    private void txtPacienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteTelefoneActionPerformed

    private void txtPacienteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteCPFActionPerformed

    private void txtPacienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteNomeActionPerformed

    private void txtIdPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPacientesActionPerformed

    
    public void limparCampos(){
        txtPacienteNome.setText("");
        txtPacienteSenha.setText("");
        txtPacienteIdade.setText("");
        txtPacienteTelefone.setText("");
        txtPacienteCPF.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCadastroPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCadastroPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCadastroPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCadastroPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCadastroPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtIdPacientes;
    private javax.swing.JTextField txtPacienteCPF;
    private javax.swing.JTextField txtPacienteIdade;
    private javax.swing.JTextField txtPacienteNome;
    private javax.swing.JTextField txtPacienteSenha;
    private javax.swing.JTextField txtPacienteTelefone;
    // End of variables declaration//GEN-END:variables
}
