/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Entidades.Medicos;
import Entidades.Paciente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import telas.ModalCadastros.ModalCadastrarPacientes;
import telas.ModalEditar.EditarCadastroPacientes;

/**
 *
 * @author Davy
 */
public class AdminCadastrarPacientes extends javax.swing.JFrame {

    /**
     * Creates new form AdminCadastrarPacientes
     */
    public AdminCadastrarPacientes() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMedicos = new javax.swing.JButton();
        btnModalCadastrarPacientes = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePacientes = new javax.swing.JTable();
        btnAtualizarTabela = new javax.swing.JButton();
        btnEditarPacientes = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnTelaDashboard = new javax.swing.JButton();
        ImgTelaCadastrarPacientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnMedicos.setContentAreaFilled(false);
        btnMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicos);
        btnMedicos.setBounds(10, 370, 280, 60);

        btnModalCadastrarPacientes.setContentAreaFilled(false);
        btnModalCadastrarPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModalCadastrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalCadastrarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnModalCadastrarPacientes);
        btnModalCadastrarPacientes.setBounds(950, 70, 240, 50);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtSearch.setBorder(null);
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch);
        txtSearch.setBounds(520, 70, 220, 50);

        btnSearch.setBorder(null);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(750, 60, 50, 60);

        btnQuit.setText("Sair");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(100, 510, 90, 24);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Admin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 240, 40, 20);

        TablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Senha", "Idade", "Telefone", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablePacientes);
        if (TablePacientes.getColumnModel().getColumnCount() > 0) {
            TablePacientes.getColumnModel().getColumn(0).setResizable(false);
            TablePacientes.getColumnModel().getColumn(1).setResizable(false);
            TablePacientes.getColumnModel().getColumn(2).setResizable(false);
            TablePacientes.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 280, 960, 390);

        btnAtualizarTabela.setText("Atualizar Tabela");
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizarTabela);
        btnAtualizarTabela.setBounds(400, 240, 130, 30);

        btnEditarPacientes.setText("Editar");
        btnEditarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarPacientes);
        btnEditarPacientes.setBounds(650, 240, 130, 30);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(890, 240, 130, 30);

        btnTelaDashboard.setContentAreaFilled(false);
        btnTelaDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaDashboard);
        btnTelaDashboard.setBounds(0, 440, 300, 50);

        ImgTelaCadastrarPacientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy\\Documents\\NetBeansProjects\\projetoA3psc\\src\\main\\java\\imgs\\ImgTelaAdminCadastrarPacientes.png")); // NOI18N
        getContentPane().add(ImgTelaCadastrarPacientes);
        ImgTelaCadastrarPacientes.setBounds(0, 0, 1260, 710);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        // TODO add your handling code here:
        dispose();
        
        AdminCadastrarMedicos btnFormTelaMedicos= new AdminCadastrarMedicos();
        btnFormTelaMedicos.setVisible(true);
    }//GEN-LAST:event_btnMedicosActionPerformed

    private void btnModalCadastrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalCadastrarPacientesActionPerformed
        // TODO add your handling code here:
        ModalCadastrarPacientes modal = new ModalCadastrarPacientes();
        modal.setVisible(true);
        
        atualizarTabela();
    }//GEN-LAST:event_btnModalCadastrarPacientesActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Paciente pacientes = new Paciente();
        
        if (!txtSearch.getText().equals("")) {
            TablePacientes.setModel(pacientes.pesquisarPacientes(txtSearch.getText()));
        } else {
            TablePacientes.setModel(pacientes.mostrarPacientes());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        dispose();

        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // TODO add your handling code here:
        atualizarTabela();
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    private void btnEditarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacientesActionPerformed
        // TODO add your handling code here:
        Paciente paciente = new Paciente();
        int selectedRow = TablePacientes.getSelectedRow();
        
        if(selectedRow != 1){
            Object id = TablePacientes.getValueAt(selectedRow, 0);
            Object nome = TablePacientes.getValueAt(selectedRow, 1);
            Object senha = TablePacientes.getValueAt(selectedRow, 2);
            Object idade = TablePacientes.getValueAt(selectedRow, 3);
            Object telefone = TablePacientes.getValueAt(selectedRow, 4);
            Object cpf = TablePacientes.getValueAt(selectedRow, 5);

            paciente.setId(id);
            paciente.setNome(nome.toString());
            paciente.setSenha(senha.toString());
            paciente.setIdade(Integer.parseInt(idade.toString()));
            paciente.setTelefone(telefone.toString());
            paciente.setCPF(Integer.parseInt(cpf.toString()));
            
        }
        
        EditarCadastroPacientes editarCadastroPacientes = new EditarCadastroPacientes(paciente);
        editarCadastroPacientes.setVisible(true);
         
    }//GEN-LAST:event_btnEditarPacientesActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        int fetchDelete = JOptionPane.showConfirmDialog(btnDeletar, "Você tem certeza que deseja deletar?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (fetchDelete == JOptionPane.YES_OPTION) {
            Paciente paciente = new Paciente();
            int selectedRow = TablePacientes.getSelectedRow();

            if (selectedRow != -1) {
                Object id = TablePacientes.getValueAt(selectedRow, 0);
                paciente.setId(id);
            }

            try {
                paciente.deletarPacientes();
            } catch (SQLException ex) {
                Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(Level.SEVERE, null, ex);
            }

            atualizarTabela();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnTelaDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaDashboardActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_btnTelaDashboardActionPerformed

    public void atualizarTabela(){
        Paciente paciente = new Paciente();
        TablePacientes.setModel(paciente.mostrarPacientes());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCadastrarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgTelaCadastrarPacientes;
    public javax.swing.JTable TablePacientes;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditarPacientes;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnModalCadastrarPacientes;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTelaDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
