/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import telas.ModalCadastros.ModalCadastrarMedicos;
import Entidades.Medicos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import telas.ModalEditar.EditarCadastroMedico;

/**
 *
 * @author Davy
 */
public class AdminCadastrarMedicos extends javax.swing.JFrame {

    /**
     * Creates new form AdminCadastrarMedicos
     */
    public AdminCadastrarMedicos() {
        initComponents();
        atualizarTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTelaDashboard = new javax.swing.JButton();
        btnModalCadastrarMedicos = new javax.swing.JButton();
        txtSearchMedico = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMedicos = new javax.swing.JTable();
        btnAtualizarTabela = new javax.swing.JButton();
        btnModalEdit = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTelaPacientes = new javax.swing.JButton();
        ImgTelaCadastrarMedicos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        btnTelaDashboard.setContentAreaFilled(false);
        btnTelaDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaDashboard);
        btnTelaDashboard.setBounds(0, 440, 300, 50);

        btnModalCadastrarMedicos.setContentAreaFilled(false);
        btnModalCadastrarMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModalCadastrarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalCadastrarMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnModalCadastrarMedicos);
        btnModalCadastrarMedicos.setBounds(940, 73, 260, 50);

        txtSearchMedico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSearchMedico.setForeground(new java.awt.Color(102, 102, 102));
        txtSearchMedico.setBorder(null);
        txtSearchMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearchMedico);
        txtSearchMedico.setBounds(520, 70, 220, 50);

        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(750, 60, 50, 60);

        btnQuit.setText("Sair");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(90, 520, 90, 23);

        TableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Senha", "Especialidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableMedicos);
        if (TableMedicos.getColumnModel().getColumnCount() > 0) {
            TableMedicos.getColumnModel().getColumn(0).setResizable(false);
            TableMedicos.getColumnModel().getColumn(1).setResizable(false);
            TableMedicos.getColumnModel().getColumn(2).setResizable(false);
            TableMedicos.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 290, 960, 420);

        btnAtualizarTabela.setText("Atualizar Tabela");
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizarTabela);
        btnAtualizarTabela.setBounds(410, 240, 130, 30);

        btnModalEdit.setText("Editar");
        btnModalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnModalEdit);
        btnModalEdit.setBounds(640, 240, 140, 30);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(890, 240, 130, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Admin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 240, 40, 20);

        btnTelaPacientes.setContentAreaFilled(false);
        btnTelaPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaPacientes);
        btnTelaPacientes.setBounds(0, 310, 300, 50);

        ImgTelaCadastrarMedicos.setIcon(new javax.swing.ImageIcon("D:\\1 SEM\\Programação de soluções computacionais\\projetoA3psc\\src\\main\\java\\imgs\\ImgTelaAdminCadastrarMedicos.png")); // NOI18N
        getContentPane().add(ImgTelaCadastrarMedicos);
        ImgTelaCadastrarMedicos.setBounds(0, 0, 1260, 710);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaDashboardActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_btnTelaDashboardActionPerformed

    private void btnModalCadastrarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalCadastrarMedicosActionPerformed
        // TODO add your handling code here:

        ModalCadastrarMedicos modal = new ModalCadastrarMedicos();
        modal.setVisible(true);

        atualizarTabela();

    }//GEN-LAST:event_btnModalCadastrarMedicosActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        dispose();

        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void txtSearchMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchMedicoActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtSearchMedicoActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Medicos medicos = new Medicos();

        if (!txtSearchMedico.getText().equals("")) {
            TableMedicos.setModel(medicos.pesquisarMedicos(txtSearchMedico.getText()));
        } else {
            TableMedicos.setModel(medicos.mostrarMedicos());
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // TODO add your handling code here:
        atualizarTabela();
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed


    private void btnModalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalEditActionPerformed
        // TODO add your handling code here:

        Medicos medicos = new Medicos();
        int selectedRow = TableMedicos.getSelectedRow();

        if (selectedRow != -1) {
            Object id = TableMedicos.getValueAt(selectedRow, 0);
            Object name = TableMedicos.getValueAt(selectedRow, 1);
            Object senha = TableMedicos.getValueAt(selectedRow, 2);
            Object especialidade = TableMedicos.getValueAt(selectedRow, 3);

            medicos.setId(id);
            medicos.setNome(name.toString());
            medicos.setSenha(senha.toString());
            medicos.setEspecialidade(especialidade.toString());
        }

        EditarCadastroMedico modalEditarCadastro = new EditarCadastroMedico(medicos);
        modalEditarCadastro.setVisible(true);

    }//GEN-LAST:event_btnModalEditActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:

        int fetchDelete = JOptionPane.showConfirmDialog(btnDeletar, "Você tem certeza que deseja deletar?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (fetchDelete == JOptionPane.YES_OPTION) {
            Medicos medicos = new Medicos();
            int selectedRow = TableMedicos.getSelectedRow();

            if (selectedRow != -1) {
                Object id = TableMedicos.getValueAt(selectedRow, 0);
                medicos.setId(id);
            }

            try {
                medicos.deletarMedicos();
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(btnDeletar, "Esse contém consultas agendadas!!!!","ERROR",  JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(Level.SEVERE, null, ex);
            }

            atualizarTabela();
        }


    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnTelaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaPacientesActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminCadastrarPacientes adminCadastrarPacientes = new AdminCadastrarPacientes();
        adminCadastrarPacientes.setVisible(true);
    }//GEN-LAST:event_btnTelaPacientesActionPerformed

    public void atualizarTabela() {
        Medicos medicos = new Medicos();
        TableMedicos.setModel(medicos.mostrarMedicos());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCadastrarMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgTelaCadastrarMedicos;
    public javax.swing.JTable TableMedicos;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnModalCadastrarMedicos;
    private javax.swing.JButton btnModalEdit;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTelaDashboard;
    private javax.swing.JButton btnTelaPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearchMedico;
    // End of variables declaration//GEN-END:variables
}
