/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Entidades.Medicos;
import Entidades.Paciente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Davy
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        try {
            painelDeDados();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void painelDeDados() throws SQLException{
        Medicos medicos = new Medicos();
        labelQtdMedicos.setText(Integer.toString(medicos.quantidadeMedicos()));
        
        Paciente paciente = new Paciente();
        labelQtdPacientes.setText(Integer.toString(paciente.quantidadePacientes()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTelaPacientes = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelQtdPacientes = new javax.swing.JLabel();
        labelQtdMedicos = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnTelaPacientes.setContentAreaFilled(false);
        btnTelaPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaPacientes);
        btnTelaPacientes.setBounds(0, 310, 300, 50);

        btnMedicos.setContentAreaFilled(false);
        btnMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicos);
        btnMedicos.setBounds(10, 370, 280, 60);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Admin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 250, 35, 16);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Médicos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 90, 100, 120);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pacientes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(900, 80, 120, 140);

        labelQtdPacientes.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        labelQtdPacientes.setForeground(new java.awt.Color(0, 0, 0));
        labelQtdPacientes.setText("0");
        getContentPane().add(labelQtdPacientes);
        labelQtdPacientes.setBounds(1100, 200, 11, 26);

        labelQtdMedicos.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        labelQtdMedicos.setForeground(new java.awt.Color(0, 0, 0));
        labelQtdMedicos.setText("0");
        getContentPane().add(labelQtdMedicos);
        labelQtdMedicos.setBounds(680, 200, 20, 26);

        btnQuit.setText("Sair");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(90, 520, 90, 24);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy\\Documents\\NetBeansProjects\\projetoA3psc\\src\\main\\java\\imgs\\Dashboard.png")); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 720);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaPacientesActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminCadastrarPacientes btnFormTelaPacientes = new AdminCadastrarPacientes();
        btnFormTelaPacientes.setVisible(true);
    }//GEN-LAST:event_btnTelaPacientesActionPerformed

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        // TODO add your handling code here:
        dispose();

        AdminCadastrarMedicos btnFormTelaMedicos= new AdminCadastrarMedicos();
        btnFormTelaMedicos.setVisible(true);
    }//GEN-LAST:event_btnMedicosActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        dispose();

        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnTelaPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelQtdMedicos;
    private javax.swing.JLabel labelQtdPacientes;
    // End of variables declaration//GEN-END:variables
}
