/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Entidades.Admin;
import Entidades.Consulta;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import telas.ModalCadastros.ModalConsultas;

/**
 *
 * @author Davy
 */
public class PacienteConsultas extends javax.swing.JFrame {

    /**
     * Creates new form PacienteExames
     */
    public PacienteConsultas() {
        initComponents();
    }
    
    public void obterPaciente(String id, String nome){
        labelId.setText(id);
        labelNome.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuCarterinha = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsulta = new javax.swing.JTable();
        btnAtualizarTableConsulta = new javax.swing.JButton();
        btnCancelarConsulta = new javax.swing.JButton();
        btnNavMarcarConsultas = new javax.swing.JButton();
        btnNavPacienteExames = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        btnMenuCarterinha.setText("Menu");
        btnMenuCarterinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCarterinhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuCarterinha);
        btnMenuCarterinha.setBounds(10, 20, 90, 30);

        btnQuit.setText("Sair");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(10, 80, 90, 30);

        labelId.setText("jLabel1");
        getContentPane().add(labelId);
        labelId.setBounds(130, 230, 41, 16);

        labelNome.setText("jLabel2");
        getContentPane().add(labelNome);
        labelNome.setBounds(160, 250, 50, 30);

        TableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Médico", "Horário", "Especialidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableConsulta);
        if (TableConsulta.getColumnModel().getColumnCount() > 0) {
            TableConsulta.getColumnModel().getColumn(0).setResizable(false);
            TableConsulta.getColumnModel().getColumn(1).setResizable(false);
            TableConsulta.getColumnModel().getColumn(2).setResizable(false);
            TableConsulta.getColumnModel().getColumn(3).setResizable(false);
            TableConsulta.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 300, 850, 370);

        btnAtualizarTableConsulta.setText("Atualizar Consultas");
        btnAtualizarTableConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTableConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizarTableConsulta);
        btnAtualizarTableConsulta.setBounds(480, 240, 170, 24);

        btnCancelarConsulta.setText("Cancelar Consulta");
        btnCancelarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarConsulta);
        btnCancelarConsulta.setBounds(720, 240, 170, 24);

        btnNavMarcarConsultas.setBorder(null);
        btnNavMarcarConsultas.setContentAreaFilled(false);
        btnNavMarcarConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavMarcarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavMarcarConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnNavMarcarConsultas);
        btnNavMarcarConsultas.setBounds(10, 310, 400, 60);

        btnNavPacienteExames.setBorder(null);
        btnNavPacienteExames.setContentAreaFilled(false);
        btnNavPacienteExames.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavPacienteExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavPacienteExamesActionPerformed(evt);
            }
        });
        getContentPane().add(btnNavPacienteExames);
        btnNavPacienteExames.setBounds(0, 440, 400, 60);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Davy\\Documents\\NetBeansProjects\\projetoA3psc\\src\\main\\java\\imgs\\ImgTelaPacienteConsultas.png")); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1280, 720));
        background.setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(background);
        background.setBounds(-10, 0, 1288, 728);

        setSize(new java.awt.Dimension(1280, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        dispose();

        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnMenuCarterinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCarterinhaActionPerformed
        // TODO add your handling code here:        
        Consulta consulta = new Consulta();
        try {
            Admin.authenticatePaciente(labelNome.getText(), consulta.obterSenhaByNome(labelNome.getText()));
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(PacienteConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_btnMenuCarterinhaActionPerformed

    private void btnAtualizarTableConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTableConsultaActionPerformed
        // TODO add your handling code here:
        atualizarTabela();
    }//GEN-LAST:event_btnAtualizarTableConsultaActionPerformed

    private void btnCancelarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConsultaActionPerformed
        // TODO add your handling code here:
        int fetchDelete = JOptionPane.showConfirmDialog(btnCancelarConsulta, "Você tem certeza que deseja cancelar essa consulta?",
                "Confirmação de Cancelamento de consulta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(fetchDelete == JOptionPane.YES_OPTION){
            Consulta consulta = new Consulta();
            int selectedRow = TableConsulta.getSelectedRow();
            
            if (selectedRow != -1) {
                Object idConsulta = TableConsulta.getValueAt(selectedRow, 0);
                consulta.setID_con(Integer.parseInt(idConsulta.toString()));
            }
            
            try {
                consulta.deletarConsulta();
            } catch (SQLException ex) {
                Logger.getLogger(AdminCadastrarMedicos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            atualizarTabela();
        }
    }//GEN-LAST:event_btnCancelarConsultaActionPerformed

    private void btnNavMarcarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMarcarConsultasActionPerformed
        // TODO add your handling code here:
        ModalConsultas modalConsultas = new ModalConsultas();
        modalConsultas.setVisible(true);
        modalConsultas.obterIdPaciente(labelId);

    }//GEN-LAST:event_btnNavMarcarConsultasActionPerformed

    private void btnNavPacienteExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavPacienteExamesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PacienteExames pacienteExames = new PacienteExames();
        pacienteExames.obterPaciente(labelId.getText(), labelNome.getText());
        pacienteExames.setVisible(true);
    }//GEN-LAST:event_btnNavPacienteExamesActionPerformed

    private void atualizarTabela(){
        TableConsulta.setModel(Consulta.mostrarConsultasPaciente(labelId.getText()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableConsulta;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAtualizarTableConsulta;
    private javax.swing.JButton btnCancelarConsulta;
    private javax.swing.JButton btnMenuCarterinha;
    private javax.swing.JButton btnNavMarcarConsultas;
    private javax.swing.JButton btnNavPacienteExames;
    private javax.swing.JButton btnQuit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
