/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.ModalCadastros;

import Entidades.Consulta;
import Entidades.Exames;
import com.toedter.calendar.JCalendar;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Davy
 */
public class ModalMarcarExames extends javax.swing.JFrame {

    private String labelId;
    private JDialog calendarDialog;
    private JCalendar calendar;

    /**
     * Creates new form ModalMarcarExames
     */
    public ModalMarcarExames() {
        initComponents();
        try {
            Exames.listarTipoExame(cbCategorias);
        } catch (SQLException ex) {
            Logger.getLogger(ModalMarcarExames.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void obterIdMedico(JLabel labelId) {
        this.labelId = labelId.getText();
       /* try {
            Exames.listarPacientes(cbPacientes, this.labelId);
        } catch (SQLException ex) {
            Logger.getLogger(ModalMarcarExames.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
    
    public void obterIdConsulta(String id){
        txtIdConsulta.setText(id);
    }
    
    public void obterPacienteNome(String id){
        txtIdPaciente.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarExame = new javax.swing.JButton();
        btnSelecionarData = new javax.swing.JButton();
        txtEscolherData = new javax.swing.JTextField();
        cbCategorias = new javax.swing.JComboBox<>();
        btnDeletarCategoriaExame = new javax.swing.JButton();
        btnNovaCategoriaExame = new javax.swing.JButton();
        txtIdConsulta = new javax.swing.JTextField();
        txtIdPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnCadastrarExame.setText("Marcar Exame");
        btnCadastrarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarExameActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarExame);
        btnCadastrarExame.setBounds(130, 280, 190, 24);

        btnSelecionarData.setText("Selecionar Data");
        btnSelecionarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarData);
        btnSelecionarData.setBounds(20, 90, 170, 24);

        txtEscolherData.setToolTipText("");
        txtEscolherData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscolherDataActionPerformed(evt);
            }
        });
        getContentPane().add(txtEscolherData);
        txtEscolherData.setBounds(270, 90, 170, 24);

        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });
        getContentPane().add(cbCategorias);
        cbCategorias.setBounds(20, 160, 180, 26);

        btnDeletarCategoriaExame.setText("Deletar Categoria");
        btnDeletarCategoriaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarCategoriaExameActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarCategoriaExame);
        btnDeletarCategoriaExame.setBounds(270, 160, 170, 24);

        btnNovaCategoriaExame.setText("Inserir categoria de exame");
        btnNovaCategoriaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCategoriaExameActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovaCategoriaExame);
        btnNovaCategoriaExame.setBounds(20, 220, 430, 24);

        txtIdConsulta.setEnabled(false);
        txtIdConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdConsulta);
        txtIdConsulta.setBounds(20, 30, 170, 24);

        txtIdPaciente.setEnabled(false);
        getContentPane().add(txtIdPaciente);
        txtIdPaciente.setBounds(270, 30, 180, 24);

        setSize(new java.awt.Dimension(501, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarDataActionPerformed
        // TODO add your handling code here:

        calendarDialog = new JDialog(this, "Calendário", false);

        calendarDialog.setSize(400, 400);
        calendarDialog.setLayout(new BorderLayout());
        calendarDialog.setResizable(false);

        calendar = new JCalendar();
        calendarDialog.add(calendar, BorderLayout.CENTER);

        JButton btnSelecionarData = new JButton("Selecionar");
        btnSelecionarData.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dataSelecionada = calendar.getDate();
                Date dataAtual = new Date();

                if (dataSelecionada.getDate() <= dataAtual.getDate()) {
                    JOptionPane.showConfirmDialog(null, "Data inválida!!", "ERROR", JOptionPane.WARNING_MESSAGE);
                } else {
                    SimpleDateFormat formatarData = new SimpleDateFormat("dd-MM-yyyy");
                    txtEscolherData.setText(formatarData.format(dataSelecionada));
                    calendarDialog.dispose();
                }
            }
        });

        calendarDialog.add(btnSelecionarData, BorderLayout.SOUTH);
        calendarDialog.setLocationRelativeTo(this);
        calendarDialog.setVisible(true);
    }//GEN-LAST:event_btnSelecionarDataActionPerformed

    private void txtEscolherDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscolherDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscolherDataActionPerformed

    private void btnNovaCategoriaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCategoriaExameActionPerformed
        // TODO add your handling code here:
        String novaCategoria = JOptionPane.showInputDialog(this, "Informe a nova categoria", "Nova Categoria", JOptionPane.INFORMATION_MESSAGE);

        if (!novaCategoria.isEmpty()) {
            cbCategorias.addItem(novaCategoria);
        }
    }//GEN-LAST:event_btnNovaCategoriaExameActionPerformed

    private void btnDeletarCategoriaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarCategoriaExameActionPerformed
        // TODO add your handling code here:
        Object selecionadaCategoria = cbCategorias.getSelectedItem();

        int deletarCategoria = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja deletar essa categoria (" + selecionadaCategoria + ")", "Deletar Categoria", JOptionPane.YES_NO_CANCEL_OPTION);

        if (deletarCategoria == JOptionPane.YES_OPTION) {
            cbCategorias.removeItem(selecionadaCategoria);
        }
    }//GEN-LAST:event_btnDeletarCategoriaExameActionPerformed

    private void btnCadastrarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarExameActionPerformed
        // TODO add your handling code here:
        try {
            Exames exames = new Exames();
           
  
            exames.setData(txtEscolherData.getText());
            exames.setTipoExam(cbCategorias.getSelectedItem().toString());
            exames.setID_con(Integer.parseInt(txtIdConsulta.getText()));
            exames.setID_med(Integer.parseInt(labelId));

            int obterIdPaciente = exames.obterIdPacienteByNome(txtIdPaciente.getText());
            exames.setID_pac(obterIdPaciente);
            
            
             if (txtEscolherData.getText().isEmpty()) {
                JOptionPane.showConfirmDialog(null, "Data inválida!!", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else {
                exames.agendarExame();
                exames.deletarConsulta();
                limparCampos();
            }

        } catch (SQLException ex) {
            Logger.getLogger(ModalConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCadastrarExameActionPerformed

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void txtIdConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdConsultaActionPerformed

    public void limparCampos(){
        txtEscolherData.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalMarcarExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalMarcarExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalMarcarExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalMarcarExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalMarcarExames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarExame;
    private javax.swing.JButton btnDeletarCategoriaExame;
    private javax.swing.JButton btnNovaCategoriaExame;
    private javax.swing.JButton btnSelecionarData;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JTextField txtEscolherData;
    private javax.swing.JTextField txtIdConsulta;
    private javax.swing.JTextField txtIdPaciente;
    // End of variables declaration//GEN-END:variables
}
